name: linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        concretizer: ['original', 'clingo']
        event_name: ${{ github.event_name }}
        exclude:
        - {event_name: pull_request, python-version: 3.5, concretizer: original}
        - {event_name: pull_request, python-version: 3.5, concretizer: clingo}
        - {event_name: pull_request, python-version: 3.6, concretizer: original}
        - {event_name: pull_request, python-version: 3.6, concretizer: clingo}
        - {event_name: pull_request, python-version: 3.7, concretizer: original}
        - {event_name: pull_request, python-version: 3.7, concretizer: clingo}
        - {event_name: pull_request, python-version: 3.8, concretizer: original}
        - {event_name: pull_request, python-version: 3.8, concretizer: clingo}
    steps:
    - name: Run
      run: |
        echo ${{ matrix.event_name }} ${{ python-version }} ${{ concretizer }}
