name: linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        concretizer: ['original', 'clingo']
        is_pr:
        - ${{ github.event_name == 'pull_request' }}
        exclude:
        - {is_pr: true, python-version: 3.5, concretizer: original}
        - {is_pr: true, python-version: 3.5, concretizer: clingo}
        - {is_pr: true, python-version: 3.6, concretizer: original}
        - {is_pr: true, python-version: 3.6, concretizer: clingo}
        - {is_pr: true, python-version: 3.7, concretizer: original}
        - {is_pr: true, python-version: 3.7, concretizer: clingo}
        - {is_pr: true, python-version: 3.8, concretizer: original}
        - {is_pr: true, python-version: 3.8, concretizer: clingo}
    steps:
    - name: Run
      run: |
        echo ${{ matrix.is_pr }} ${{ matrix.python-version }} ${{ matrix.concretizer }}
